import {CHARACTERS,getCharacter,characterEffects} from '../simulation/characters.js';
import {pointRecoveryRate} from '../simulation/stamina.js';
export function characterPicker(selected:string,opponent:boolean,unlocked=false){
 const requested=getCharacter(selected),c=requested.hidden&&!unlocked?getCharacter():requested,e=characterEffects(c.id),pct=(n:number)=>`${n>=1?'+':''}${Math.round((n-1)*1000)/10}%`;
 const available=CHARACTERS.filter(x=>!x.hidden||unlocked);
 const stats=[['移动','movement'],['正手','forehand'],['反手','backhand'],['截击','volley'],['发球','serve'],['体力','stamina']] as const;
 return `<div class="overlay"><section class="panel character-panel"><div class="panel-top"><span>${opponent?'练习对手':'选择你的球员'}</span><button class="icon-button" data-action="close-characters" aria-label="返回角色选择前的页面">×</button></div><h2><button class="character-secret-title" data-action="hidden-master">找到你的打法。</button></h2><p>${unlocked?'九位普通球员 + 一位隐藏大佬，全部免费使用。':'九位球员免费使用，各有所长。'}利手决定正反手侧，单反与双反有各自的动作和站位。滑动方向保持一致。</p>
 <div class="character-grid">${available.map(x=>`<button class="character-card ${x.id===c.id?'selected':''} ${x.hidden?'hidden-master-card':''}" style="--character-color:${x.color}" data-action="pick-character-${x.id}" aria-pressed="${x.id===c.id}"><img src="/portraits/${x.id}.png" alt="${x.name}人物外观"/><strong>${x.name}</strong><span>${x.role}</span><small>${x.hidden?'全属性 99 · ':''}${x.handedness==='left'?'左手':'右手'} · ${x.backhandStyle==='one-handed'?'单反':'双反'}</small></button>`).join('')}</div>
 <div class="character-detail" style="--character-color:${c.color}"><h3>${c.name}<span>${c.role}</span></h3><p><b>打法</b> ${c.handedness==='left'?'左手持拍，正反手侧与右手球员相反':'右手持拍'} · ${c.backhandStyle==='one-handed'?'单手反拍：更靠前迎球，非持拍臂展开平衡':'双手反拍：双手握柄共同发力'}<br/><b>擅长</b> ${c.strength}<br/><b>短板</b> ${c.weakness}</p><div class="character-stats">${stats.map(([label,key])=>`<div><span>${label}</span><meter min="0" max="100" value="${c.stats[key]}">${c.stats[key]}</meter><b>${c.stats[key]}</b></div>`).join('')}</div>
 <p class="character-effects"><b>实际效果 · 相对林岳</b><br/>移动与起步 ${pct(e.movement)}；正手球速系数 ${pct(e.forehand)}、反手 ${pct(e.backhand)}、截击 ${pct(e.volley)}、发球 ${pct(e.serve)}；体力消耗系数 ${pct(e.drain)}、恢复 ${pct(e.recovery)}。</p>
 <p><b>分末恢复</b> 返还本分已扣总体力的 ${Math.round(pointRecoveryRate(c.id)*1000)/10}%（最高 90%）。</p>
 <details><summary data-action="character-attributes">这些属性如何影响比赛？</summary><p>所有球员使用同一规则，以 60 点为基准。每高 1 点，移动与起步、正手球速系数增加 1.2%；反手、截击、发球球速系数增加 2.5%；体力消耗系数减少 2%、恢复增加 2%。低于 60 点则反向变化。每分有独立体力条，消耗按 20% 折算到总体力，一分最多扣总体力 20 个百分点。分结束按角色恢复属性返还本分已扣总体力的一部分，上限 90%；下一分只重置本分条，总体力保留。一发失误后的二发仍是同一分，不重置或返还。有效体力＝本分体力×总体力，用于跑速和击球；跳身救球概率单独使用总体力，满值90%、1/3及以下10%。实际球速仍受过网高度和飞行时间约束；更强的击球会额外消耗体力。你和对手规则相同，重新开一场比赛才同时满体力。</p></details></div>
 <button class="primary" data-action="confirm-characters">${opponent?'使用这位练习对手':'使用这位球员'} →</button><p class="small-note">同角色也可对战 · 开赛后锁定选择</p></section></div>`;
}
