import {CHARACTERS,getCharacter,characterEffects} from '../simulation/characters.js';
export function characterPicker(selected:string,opponent:boolean){
 const c=getCharacter(selected),e=characterEffects(c.id),pct=(n:number)=>`${n>=1?'+':''}${Math.round((n-1)*1000)/10}%`;
 const stats=[['移动','movement'],['正手','forehand'],['反手','backhand'],['截击','volley'],['发球','serve'],['体力','stamina']] as const;
 return `<div class="overlay"><section class="panel character-panel"><div class="panel-top"><span>${opponent?'练习对手':'选择你的球员'}</span><button class="icon-button" data-action="close-characters" aria-label="返回角色选择前的页面">×</button></div><h2>找到你的打法。</h2><p>九位球员免费使用，各有所长。利手决定正反手侧，单反与双反有各自的动作和站位。滑动方向保持一致。</p>
 <div class="character-grid">${CHARACTERS.map(x=>`<button class="character-card ${x.id===c.id?'selected':''}" style="--character-color:${x.color}" data-action="pick-character-${x.id}" aria-pressed="${x.id===c.id}"><img src="/portraits/${x.id}.png" alt="${x.name}人物外观"/><strong>${x.name}</strong><span>${x.role}</span><small>${x.handedness==='left'?'左手':'右手'} · ${x.backhandStyle==='one-handed'?'单反':'双反'}</small></button>`).join('')}</div>
 <div class="character-detail" style="--character-color:${c.color}"><h3>${c.name}<span>${c.role}</span></h3><p><b>打法</b> ${c.handedness==='left'?'左手持拍，正反手侧与右手球员相反':'右手持拍'} · ${c.backhandStyle==='one-handed'?'单手反拍：更靠前迎球，非持拍臂展开平衡':'双手反拍：双手握柄共同发力'}<br/><b>擅长</b> ${c.strength}<br/><b>短板</b> ${c.weakness}</p><div class="character-stats">${stats.map(([label,key])=>`<div><span>${label}</span><meter min="0" max="100" value="${c.stats[key]}">${c.stats[key]}</meter><b>${c.stats[key]}</b></div>`).join('')}</div>
 <details><summary>这些属性如何影响比赛？</summary><p>相对林岳：移动与起步 ${pct(e.movement)}；正手球速 ${pct(e.forehand)}、反手 ${pct(e.backhand)}、截击 ${pct(e.volley)}、发球 ${pct(e.serve)}；体力消耗 ${pct(e.drain)}、恢复 ${pct(e.recovery)}。击球仍受过网高度和当前体力约束。更强的击球会略多消耗体力。球速档位由你的手势决定。</p></details></div>
 <button class="primary" data-action="close-characters">${opponent?'使用这位练习对手':'使用这位球员'} →</button><p class="small-note">同角色也可对战 · 开赛后锁定选择</p></section></div>`;
}
